from __future__ import annotations

from typing import Any

from app.geo.fresnel_v2 import (
    analyze_fresnel_profile,
    profile_to_fresnel_samples,
)


VALID_SURFACE_TYPES = {
    "NONE",
    "BUILDING",
    "TREE",
    "VEGETATION",
    "OTHER",
}


def normalize_surface_type(
    value: str | None,
) -> str:
    if not value:
        return "NONE"

    value = value.upper().strip()

    if value not in VALID_SURFACE_TYPES:
        return "OTHER"

    return value


def build_surface_profile(
    *,
    terrain_profile: list[dict[str, Any]],
    surface_obstructions: list[
        dict[str, Any]
    ] | None = None,
) -> list[dict[str, Any]]:
    """
    Merge DEM terrain with DSM/clutter
    heights.

    terrain_profile point:
    {
        "latitude": ...,
        "longitude": ...,
        "elevation_m": ...
    }

    obstruction:
    {
        "sample_index": 10,
        "height_m": 18,
        "surface_type": "BUILDING",
        "source": "OSM",
        "confidence": 0.8,
        "osm_id": ...,
        "path_offset_m": ...,
        "along_path_m": ...,
        "path_fraction": ...
    }

    Result keeps ground elevation separate
    from surface elevation and preserves
    obstruction provenance.
    """

    if len(terrain_profile) < 3:
        raise ValueError(
            "terrain_profile must contain "
            "at least 3 points"
        )

    obstruction_by_index: dict[
        int,
        dict[str, Any],
    ] = {}

    for item in (
        surface_obstructions or []
    ):
        index = int(
            item["sample_index"]
        )

        if (
            index < 0
            or index >= len(
                terrain_profile
            )
        ):
            raise ValueError(
                f"Invalid sample_index: {index}"
            )

        height_m = float(
            item.get(
                "height_m",
                0.0,
            )
        )

        if height_m < 0:
            raise ValueError(
                "surface height cannot be "
                "negative"
            )

        existing = (
            obstruction_by_index.get(
                index
            )
        )

        # If multiple surface candidates map
        # to the same DEM sample, retain the
        # tallest obstruction together with
        # its complete provenance.
        if (
            existing is None
            or height_m
            > float(
                existing.get(
                    "height_m",
                    0.0,
                )
            )
        ):
            obstruction_by_index[index] = {
                **item,
                "height_m": height_m,
            }

    result: list[
        dict[str, Any]
    ] = []

    for index, point in enumerate(
        terrain_profile
    ):
        ground_m = float(
            point[
                "elevation_m"
            ]
        )

        obstruction = (
            obstruction_by_index.get(
                index
            )
        )

        if obstruction:
            surface_height_m = float(
                obstruction[
                    "height_m"
                ]
            )

            surface_type = (
                normalize_surface_type(
                    obstruction.get(
                        "surface_type"
                    )
                )
            )

            source = (
                obstruction.get(
                    "source"
                )
            )

            confidence = float(
                obstruction.get(
                    "confidence",
                    1.0,
                )
            )

            # Preserve optional path provenance
            # generated by project_point_to_path().
            path_offset_m = (
                obstruction.get(
                    "path_offset_m"
                )
            )

            along_path_m = (
                obstruction.get(
                    "along_path_m"
                )
            )

            path_fraction = (
                obstruction.get(
                    "path_fraction"
                )
            )

            # Preserve original OSM feature
            # provenance when available.
            osm_id = (
                obstruction.get(
                    "osm_id"
                )
            )

        else:
            surface_height_m = 0.0
            surface_type = "NONE"
            source = None
            confidence = 1.0

            path_offset_m = None
            along_path_m = None
            path_fraction = None
            osm_id = None

        confidence = max(
            0.0,
            min(
                1.0,
                confidence,
            ),
        )

        result.append(
            {
                "latitude":
                    point.get(
                        "latitude"
                    ),

                "longitude":
                    point.get(
                        "longitude"
                    ),

                "ground_elevation_m":
                    round(
                        ground_m,
                        2,
                    ),

                "surface_height_m":
                    round(
                        surface_height_m,
                        2,
                    ),

                "surface_elevation_m":
                    round(
                        ground_m
                        + surface_height_m,
                        2,
                    ),

                "surface_type":
                    surface_type,

                "surface_source":
                    source,

                "surface_confidence":
                    confidence,

                "path_offset_m":
                    (
                        obstruction.get(
                            "path_offset_m"
                        )
                        if obstruction
                        else None
                    ),

                "along_path_m":
                    (
                        obstruction.get(
                            "along_path_m"
                        )
                        if obstruction
                        else None
                    ),

                "path_fraction":
                    (
                        obstruction.get(
                            "path_fraction"
                        )
                        if obstruction
                        else None
                    ),

                "osm_id":
                    (
                        obstruction.get(
                            "osm_id"
                        )
                        if obstruction
                        else None
                    ),
            }
        )

    return result


def analyze_surface_profile(
    *,
    surface_profile: list[dict],
    path_distance_m: float,
    frequency_mhz: float,
    tx_height_m: float = 30.0,
    rx_height_m: float = 1.5,
    clearance_fraction: float = 0.60,
    k_factor: float = 4.0 / 3.0,
) -> dict:
    """
    Fresnel analysis using terrain + DSM /
    clutter heights.

    Endpoint semantics:

    - TX endpoint uses ground elevation.
    - RX endpoint uses ground elevation.
    - Interior points use surface elevation.

    This prevents a building/tree/vegetation
    obstruction at an antenna endpoint from
    artificially raising the antenna base.

    The Fresnel analyzer itself applies
    tx_height_m and rx_height_m to the
    endpoint elevations.
    """

    if len(surface_profile) < 3:
        raise ValueError(
            "surface_profile must contain "
            "at least 3 points"
        )

    if path_distance_m <= 0:
        raise ValueError(
            "path_distance_m must be "
            "greater than 0"
        )

    if frequency_mhz <= 0:
        raise ValueError(
            "frequency_mhz must be "
            "greater than 0"
        )

    if tx_height_m < 0:
        raise ValueError(
            "tx_height_m cannot be negative"
        )

    if rx_height_m < 0:
        raise ValueError(
            "rx_height_m cannot be negative"
        )

    if not 0 < clearance_fraction <= 1:
        raise ValueError(
            "clearance_fraction must be "
            "greater than 0 and less "
            "than or equal to 1"
        )

    if k_factor <= 0:
        raise ValueError(
            "k_factor must be greater "
            "than 0"
        )

    fresnel_input: list[
        dict[str, Any]
    ] = []

    intervals = (
        len(surface_profile) - 1
    )

    for index, point in enumerate(
        surface_profile
    ):
        fraction = (
            index / intervals
        )

        # IMPORTANT:
        #
        # The first and last profile points
        # represent the actual TX/RX antenna
        # locations.
        #
        # Their clutter height must NOT become
        # part of the antenna base elevation.
        #
        # TX/RX -> ground elevation
        # Interior -> surface/DSM elevation
        is_endpoint = (
            index == 0
            or index
            == len(surface_profile) - 1
        )

        if is_endpoint:
            effective_elevation_m = float(
                point[
                    "ground_elevation_m"
                ]
            )
        else:
            effective_elevation_m = float(
                point[
                    "surface_elevation_m"
                ]
            )

        fresnel_input.append(
            {
                "distance_m":
                    round(
                        path_distance_m
                        * fraction,
                        2,
                    ),

                "elevation_m":
                    round(
                        effective_elevation_m,
                        2,
                    ),

                "latitude":
                    point.get(
                        "latitude"
                    ),

                "longitude":
                    point.get(
                        "longitude"
                    ),
            }
        )

    result = (
        analyze_fresnel_profile(
            samples=fresnel_input,
            frequency_mhz=frequency_mhz,
            tx_height_m=tx_height_m,
            rx_height_m=rx_height_m,
            clearance_fraction=(
                clearance_fraction
            ),
            k_factor=k_factor,
        )
    )

    # -----------------------------------------
    # STEP 32E.2
    #
    # Enrich worst obstruction with the
    # original surface/DSM provenance.
    #
    # IMPORTANT:
    #
    # fresnel_v2 analyzed the effective
    # surface elevation. Therefore preserve
    # that original geometric value before
    # restoring the physical ground elevation
    # semantics.
    # -----------------------------------------

    worst = result.get(
        "worst_obstruction"
    )

    if worst is not None:
        distance_ratio = worst.get(
            "distance_ratio"
        )

        if distance_ratio is not None:
            ratio = float(
                distance_ratio
            )

            ratio = max(
                0.0,
                min(
                    1.0,
                    ratio,
                ),
            )

            index = round(
                ratio
                * (
                    len(
                        surface_profile
                    )
                    - 1
                )
            )

            index = max(
                0,
                min(
                    len(
                        surface_profile
                    ) - 1,
                    index,
                ),
            )

            surface_point = (
                surface_profile[
                    index
                ]
            )

            worst.update(
                {
                    # Fresnel v2 used the
                    # surface elevation as its
                    # geometric input.
                    "analyzed_surface_elevation_m":
                        worst.get(
                            "terrain_elevation_m"
                        ),

                    # Restore physical ground
                    # elevation semantics for
                    # surface-aware output.
                    "terrain_elevation_m":
                        surface_point[
                            "ground_elevation_m"
                        ],

                    "ground_elevation_m":
                        surface_point[
                            "ground_elevation_m"
                        ],

                    "surface_height_m":
                        surface_point[
                            "surface_height_m"
                        ],

                    "surface_elevation_m":
                        surface_point[
                            "surface_elevation_m"
                        ],

                    "surface_type":
                        surface_point[
                            "surface_type"
                        ],

                    "surface_source":
                        surface_point[
                            "surface_source"
                        ],

                    "surface_confidence":
                        surface_point[
                            "surface_confidence"
                        ],

                    "path_offset_m":
                        (
                            surface_point.get(
                                "path_offset_m"
                            )
                            if surface_point.get(
                                "path_offset_m"
                            )
                            is not None
                            else 0.0
                        ),

                    "along_path_m":
                        (
                            surface_point.get(
                                "along_path_m"
                            )
                            if surface_point.get(
                                "along_path_m"
                            )
                            is not None
                            else worst.get(
                                "distance_m"
                            )
                        ),

                    "path_fraction":
                        (
                            surface_point.get(
                                "path_fraction"
                            )
                            if surface_point.get(
                                "path_fraction"
                            )
                            is not None
                            else worst.get(
                                "distance_ratio"
                            )
                        ),

                    "osm_id":
                        surface_point.get(
                            "osm_id"
                        ),
                }
            )

    # -----------------------------------------
    # Surface obstruction summary
    # -----------------------------------------

    obstructed_surface_points = [
        item
        for item in surface_profile
        if float(
            item[
                "surface_height_m"
            ]
        ) > 0
    ]

    building_points = [
        item
        for item in obstructed_surface_points
        if item[
            "surface_type"
        ] == "BUILDING"
    ]

    vegetation_points = [
        item
        for item in obstructed_surface_points
        if item[
            "surface_type"
        ]
        in {
            "TREE",
            "VEGETATION",
        }
    ]

    result[
        "surface_context"
    ] = {
        "surface_obstruction_points":
            len(
                obstructed_surface_points
            ),

        "building_points":
            len(
                building_points
            ),

        "vegetation_points":
            len(
                vegetation_points
            ),

        "maximum_surface_height_m":
            (
                max(
                    float(
                        item[
                            "surface_height_m"
                        ]
                    )
                    for item
                    in obstructed_surface_points
                )
                if obstructed_surface_points
                else 0.0
            ),
    }

    return result