"""add action review lifecycle

Revision ID: 34dd6c3a376a
Revises: ac09951ba97c
Create Date: 2026-09-25 17:45:23.723360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34dd6c3a376a'
down_revision: Union[str, Sequence[str], None] = 'ac09951ba97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_plans', sa.Column('reviewed_by', sa.String(length=120), nullable=True))
    op.add_column('action_plans', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('action_plans', sa.Column('review_reason', sa.Text(), nullable=True))
    op.add_column('action_plans', sa.Column('approved_for_simulation_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('action_plans', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('action_plans', sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('action_plans', sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True))

    # Backfill existing ActionPlan rows so lifecycle audit
    # history starts from a known timestamp.
    op.execute(
        """
        UPDATE action_plans
        SET status_updated_at = COALESCE(
            updated_at,
            created_at,
            CURRENT_TIMESTAMP
        )
        WHERE status_updated_at IS NULL
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_plans', 'status_updated_at')
    op.drop_column('action_plans', 'blocked_at')
    op.drop_column('action_plans', 'rejected_at')
    op.drop_column('action_plans', 'approved_for_simulation_at')
    op.drop_column('action_plans', 'review_reason')
    op.drop_column('action_plans', 'reviewed_at')
    op.drop_column('action_plans', 'reviewed_by')
    # ### end Alembic commands ###

