"""add action feedback

Revision ID: 3f658df43d7f
Revises: 465a3a6ffcd8
Create Date: 2026-09-25 20:34:45.997363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f658df43d7f'
down_revision: Union[str, Sequence[str], None] = '465a3a6ffcd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_uuid', sa.String(length=36), nullable=False),
    sa.Column('action_plan_id', sa.Integer(), nullable=False),
    sa.Column('rca_case_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('verification_id', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=120), nullable=True),
    sa.Column('feedback_status', sa.String(length=30), nullable=False),
    sa.Column('diagnosis_assessment', sa.String(length=30), nullable=False),
    sa.Column('action_assessment', sa.String(length=30), nullable=False),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('operator_confidence', sa.Float(), nullable=True),
    sa.Column('actual_root_cause', sa.String(length=120), nullable=True),
    sa.Column('actual_resolution', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_gate_status', sa.String(length=30), nullable=False),
    sa.Column('training_eligible', sa.Boolean(), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rca_case_id'], ['rca_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_id'], ['action_verifications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_plan_id', 'revision', name='uq_action_feedback_plan_revision')
    )
    op.create_index(op.f('ix_action_feedback_action_assessment'), 'action_feedback', ['action_assessment'], unique=False)
    op.create_index(op.f('ix_action_feedback_action_plan_id'), 'action_feedback', ['action_plan_id'], unique=False)
    op.create_index(op.f('ix_action_feedback_actual_root_cause'), 'action_feedback', ['actual_root_cause'], unique=False)
    op.create_index(op.f('ix_action_feedback_alert_id'), 'action_feedback', ['alert_id'], unique=False)
    op.create_index(op.f('ix_action_feedback_created_at'), 'action_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_feedback_diagnosis_assessment'), 'action_feedback', ['diagnosis_assessment'], unique=False)
    op.create_index(op.f('ix_action_feedback_feedback_status'), 'action_feedback', ['feedback_status'], unique=False)
    op.create_index(op.f('ix_action_feedback_feedback_uuid'), 'action_feedback', ['feedback_uuid'], unique=True)
    op.create_index(op.f('ix_action_feedback_quality_gate_status'), 'action_feedback', ['quality_gate_status'], unique=False)
    op.create_index(op.f('ix_action_feedback_rca_case_id'), 'action_feedback', ['rca_case_id'], unique=False)
    op.create_index(op.f('ix_action_feedback_resolution_status'), 'action_feedback', ['resolution_status'], unique=False)
    op.create_index(op.f('ix_action_feedback_training_eligible'), 'action_feedback', ['training_eligible'], unique=False)
    op.create_index(op.f('ix_action_feedback_verification_id'), 'action_feedback', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_feedback_verification_id'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_training_eligible'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_resolution_status'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_rca_case_id'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_quality_gate_status'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_feedback_uuid'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_feedback_status'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_diagnosis_assessment'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_created_at'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_alert_id'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_actual_root_cause'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_action_plan_id'), table_name='action_feedback')
    op.drop_index(op.f('ix_action_feedback_action_assessment'), table_name='action_feedback')
    op.drop_table('action_feedback')
    # ### end Alembic commands ###
