"""add action verifications

Revision ID: 465a3a6ffcd8
Revises: 63a686a043c4
Create Date: 2026-09-25 19:52:48.991017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '465a3a6ffcd8'
down_revision: Union[str, Sequence[str], None] = '63a686a043c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verification_uuid', sa.String(length=36), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('verifier_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('checks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_decision', sa.String(length=50), nullable=False),
    sa.Column('execution_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['action_simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_verifications_created_at'), 'action_verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_verifications_rollback_decision'), 'action_verifications', ['rollback_decision'], unique=False)
    op.create_index(op.f('ix_action_verifications_simulation_id'), 'action_verifications', ['simulation_id'], unique=True)
    op.create_index(op.f('ix_action_verifications_status'), 'action_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_action_verifications_verification_uuid'), 'action_verifications', ['verification_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_verifications_verification_uuid'), table_name='action_verifications')
    op.drop_index(op.f('ix_action_verifications_status'), table_name='action_verifications')
    op.drop_index(op.f('ix_action_verifications_simulation_id'), table_name='action_verifications')
    op.drop_index(op.f('ix_action_verifications_rollback_decision'), table_name='action_verifications')
    op.drop_index(op.f('ix_action_verifications_created_at'), table_name='action_verifications')
    op.drop_table('action_verifications')
    # ### end Alembic commands ###
