"""add action simulations

Revision ID: 63a686a043c4
Revises: 34dd6c3a376a
Create Date: 2026-09-25 19:38:13.219251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63a686a043c4'
down_revision: Union[str, Sequence[str], None] = '34dd6c3a376a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_uuid', sa.String(length=36), nullable=False),
    sa.Column('action_plan_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('simulation_mode', sa.String(length=30), nullable=False),
    sa.Column('simulator_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('input_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_ready', sa.Boolean(), nullable=False),
    sa.Column('rollback_ready', sa.Boolean(), nullable=False),
    sa.Column('execution_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_plan_id'], ['action_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_simulations_action_plan_id'), 'action_simulations', ['action_plan_id'], unique=False)
    op.create_index(op.f('ix_action_simulations_created_at'), 'action_simulations', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_simulations_simulation_mode'), 'action_simulations', ['simulation_mode'], unique=False)
    op.create_index(op.f('ix_action_simulations_simulation_uuid'), 'action_simulations', ['simulation_uuid'], unique=True)
    op.create_index(op.f('ix_action_simulations_status'), 'action_simulations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_simulations_status'), table_name='action_simulations')
    op.drop_index(op.f('ix_action_simulations_simulation_uuid'), table_name='action_simulations')
    op.drop_index(op.f('ix_action_simulations_simulation_mode'), table_name='action_simulations')
    op.drop_index(op.f('ix_action_simulations_created_at'), table_name='action_simulations')
    op.drop_index(op.f('ix_action_simulations_action_plan_id'), table_name='action_simulations')
    op.drop_table('action_simulations')
    # ### end Alembic commands ###
