"""add device profiles for population correlation

Revision ID: 8e76c2fd3407
Revises: 5805a3ea240f
Create Date: 2026-09-24 07:44:24.162382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# =====================================================
# REVISION IDENTIFIERS
# =====================================================

revision: str = "8e76c2fd3407"

down_revision: Union[str, Sequence[str], None] = "5805a3ea240f"

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


# =====================================================
# UPGRADE
# =====================================================

def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "device_profiles",

        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),

        sa.Column(
            "device_id",
            sa.Integer(),
            nullable=False,
        ),

        sa.Column(
            "manufacturer",
            sa.String(length=80),
            nullable=True,
        ),

        sa.Column(
            "model_name",
            sa.String(length=120),
            nullable=True,
        ),

        sa.Column(
            "os_name",
            sa.String(length=80),
            nullable=True,
        ),

        sa.Column(
            "os_version",
            sa.String(length=80),
            nullable=True,
        ),

        sa.Column(
            "firmware_version",
            sa.String(length=120),
            nullable=True,
        ),

        sa.Column(
            "modem_version",
            sa.String(length=120),
            nullable=True,
        ),

        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),

        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),

        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            ondelete="CASCADE",
        ),

        sa.PrimaryKeyConstraint(
            "id",
        ),
    )

    op.create_index(
        op.f("ix_device_profiles_device_id"),
        "device_profiles",
        ["device_id"],
        unique=True,
    )

    op.create_index(
        op.f("ix_device_profiles_firmware_version"),
        "device_profiles",
        ["firmware_version"],
        unique=False,
    )

    op.create_index(
        op.f("ix_device_profiles_manufacturer"),
        "device_profiles",
        ["manufacturer"],
        unique=False,
    )

    op.create_index(
        op.f("ix_device_profiles_model_name"),
        "device_profiles",
        ["model_name"],
        unique=False,
    )

    # NOTE:
    # spatial_ref_sys is managed by the PostGIS extension.
    # Do NOT create, alter, or drop it from Alembic migrations.

    # ### end Alembic commands ###


# =====================================================
# DOWNGRADE
# =====================================================

def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_device_profiles_model_name"),
        table_name="device_profiles",
    )

    op.drop_index(
        op.f("ix_device_profiles_manufacturer"),
        table_name="device_profiles",
    )

    op.drop_index(
        op.f("ix_device_profiles_firmware_version"),
        table_name="device_profiles",
    )

    op.drop_index(
        op.f("ix_device_profiles_device_id"),
        table_name="device_profiles",
    )

    op.drop_table(
        "device_profiles",
    )

    # NOTE:
    # spatial_ref_sys is owned by PostGIS and must not be recreated
    # by an application migration.

    # ### end Alembic commands ###