"""add action plans

Revision ID: ac09951ba97c
Revises: 57b82e89c122
Create Date: 2026-09-25 17:14:03.557272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac09951ba97c'
down_revision: Union[str, Sequence[str], None] = '57b82e89c122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_uuid', sa.String(length=36), nullable=False),
    sa.Column('rca_case_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('source_primary_cause', sa.String(length=120), nullable=False),
    sa.Column('source_confidence', sa.Float(), nullable=True),
    sa.Column('source_verifier_status', sa.String(length=40), nullable=True),
    sa.Column('action_code', sa.String(length=80), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_ref', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('execution_mode', sa.String(length=30), nullable=False),
    sa.Column('safety_gate_status', sa.String(length=30), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('auto_eligible', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('blast_radius', sa.String(length=30), nullable=False),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('rollback_required', sa.Boolean(), nullable=False),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preconditions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_checks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('planner_version', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rca_case_id'], ['rca_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plans_action_code'), 'action_plans', ['action_code'], unique=False)
    op.create_index(op.f('ix_action_plans_action_type'), 'action_plans', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_plans_action_uuid'), 'action_plans', ['action_uuid'], unique=True)
    op.create_index(op.f('ix_action_plans_alert_id'), 'action_plans', ['alert_id'], unique=False)
    op.create_index(op.f('ix_action_plans_blast_radius'), 'action_plans', ['blast_radius'], unique=False)
    op.create_index(op.f('ix_action_plans_created_at'), 'action_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_plans_device_id'), 'action_plans', ['device_id'], unique=False)
    op.create_index(op.f('ix_action_plans_execution_mode'), 'action_plans', ['execution_mode'], unique=False)
    op.create_index(op.f('ix_action_plans_rca_case_id'), 'action_plans', ['rca_case_id'], unique=False)
    op.create_index(op.f('ix_action_plans_risk_level'), 'action_plans', ['risk_level'], unique=False)
    op.create_index(op.f('ix_action_plans_safety_gate_status'), 'action_plans', ['safety_gate_status'], unique=False)
    op.create_index(op.f('ix_action_plans_source_primary_cause'), 'action_plans', ['source_primary_cause'], unique=False)
    op.create_index(op.f('ix_action_plans_status'), 'action_plans', ['status'], unique=False)
    op.create_index(op.f('ix_action_plans_target_ref'), 'action_plans', ['target_ref'], unique=False)
    op.create_index(op.f('ix_action_plans_target_type'), 'action_plans', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_plans_target_type'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_target_ref'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_status'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_source_primary_cause'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_safety_gate_status'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_risk_level'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_rca_case_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_execution_mode'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_device_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_created_at'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_blast_radius'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_alert_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_action_uuid'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_action_type'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_action_code'), table_name='action_plans')
    op.drop_table('action_plans')
    # ### end Alembic commands ###
